# This is a basic workflow to help you get started with Actions

name: DCBOT

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "nutc" ]
  pull_request:
    branches: [ "nutc" ]
  schedule:
    - cron: "* */6 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        python-version: [3.9]
        
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          
      - name: copy enviroment
        run: |
          echo "$BOT_INI" >> /home/runner/work/NutcDiscordBot/NutcDiscordBot/src/bot.ini
          echo "$VERSION_PY" >> /home/runner/work/NutcDiscordBot/NutcDiscordBot/src/ctbot/command/version.py
          echo "$guild_json" > /home/runner/work/NutcDiscordBot/NutcDiscordBot/src/config/guild.json
          echo "$MEMBER_JOIN_JSON" > /home/runner/work/NutcDiscordBot/NutcDiscordBot/src/config/member_join.json
          echo "$MEMBER_LEAVE_JSON" > /home/runner/work/NutcDiscordBot/NutcDiscordBot/src/config/member_leave.json
          echo "$REACTION_ROLE_JSON" > /home/runner/work/NutcDiscordBot/NutcDiscordBot/src/config/reaction_role.json
          echo "$SERVICE_JSON" > /home/runner/work/NutcDiscordBot/NutcDiscordBot/src/config/service.json
          echo "$TIMELABEL_JSON" > /home/runner/work/NutcDiscordBot/NutcDiscordBot/src/config/timeLabel.json
          echo "$WORDS_JSON" > /home/runner/work/NutcDiscordBot/NutcDiscordBot/src/config/words.json
        env: 
          BOT_INI: ${{secrets.BOT_INI}}
          VERSION_PY: ${{secrets.VERSION_PY}}
          guild_json: ${{secrets.GUILD_JSON}}
          MEMBER_JOIN_JSON: ${{secrets.MEMBER_JOIN_JSON}}
          MEMBER_LEAVE_JSON: ${{secrets.MEMBER_LEAVE_JSON}}
          REACTION_ROLE_JSON: ${{secrets.REACTION_ROLE_JSON}}
          SERVICE_JSON: ${{secrets.SERVICE_JSON}}
          TIMELABEL_JSON: ${{secrets.TIMELABEL_JSON}}
          WORDS_JSON: ${{secrets.WORDS_JSON}}
      
      - name: Install Dependencies
        run: python -m pip install --upgrade pip

      # Runs a single command using the runners shell
      - name: install requirments
        run: python -m pip install -r requirments.txt

      # Runs a set of commands using the runners shell
      - name: run bot
        run: |
          cd src
          python -m ctbot
